model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.ChestVQModel
  params:
    embed_dim: 256    # 512
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: chest-main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 10
    train:
      # train_path: /home/yangling/VQGAN/taming-transformers-master/data/chest_xray/train/normal.txt
      # base_path: /home/yangling/VQGAN/taming-transformers-master/data/chest_xray/train/NORMAL
      # csv_path: /home/yangling/VQGAN/taming-transformers-master/data/NIHChestX-rays/Data_Entry_2017.csv
      train_path: /home/yangling/VQGAN/taming-transformers-master/data/NIHCHestClassification/validation/Pneumothorax.txt
      base_path: /home/yangling/VQGAN/taming-transformers-master/data/NIHCHestClassification/validation/Pneumothorax
      csv_path: /home/yangling/VQGAN/taming-transformers-master/data/NIHChestX-rays/Data_Entry_2017.csv
      params:
        config:
          size: 256
    validation:
      # test_path: /home/yangling/VQGAN/taming-transformers-master/data/chest_xray/test/normal.txt
      # base_path: /home/yangling/VQGAN/taming-transformers-master/data/chest_xray/test/NORMAL
      # csv_path: /home/yangling/VQGAN/taming-transformers-master/data/NIHChestX-rays/Data_Entry_2017.csv
      test_path: /home/yangling/VQGAN/taming-transformers-master/data/NIHCHestClassification/validation/Pneumothorax.txt
      base_path: /home/yangling/VQGAN/taming-transformers-master/data/NIHCHestClassification/validation/Pneumothorax
      csv_path: /home/yangling/VQGAN/taming-transformers-master/data/NIHChestX-rays/Data_Entry_2017.csv
      params:
        config:
          size: 256
