model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.BoneVQModel
  params:
    embed_dim: 256     # 256
    n_embed: 1024   # 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: bse_main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 10
    train:
      train_path: /home/yangling/VQGAN/taming-transformers-master/data/BoneShadowX-rays/BSE_Bone_Dataset/train.txt
      bone_base_path: /home/yangling/VQGAN/taming-transformers-master/data/BoneShadowX-rays/Bone_Dataset/bonetrainRGB
      bse_base_path: /home/yangling/VQGAN/taming-transformers-master/data/BoneShadowX-rays/BSE_Bone_Dataset/trainRGB
      params:
        config:
          size: 256
    validation:
      test_path: /home/yangling/VQGAN/taming-transformers-master/data/BoneShadowX-rays/BSE_Bone_Dataset/test.txt
      bone_base_path: /home/yangling/VQGAN/taming-transformers-master/data/BoneShadowX-rays/Bone_Dataset/bonetestRGB
      bse_base_path: /home/yangling/VQGAN/taming-transformers-master/data/BoneShadowX-rays/BSE_Bone_Dataset/testRGB
      params:
        config:
          size: 256
